#ifndef	SYS_INI_H
#define SYS_INI_H

//raspored podataka u memoriji za fajl sys.ini

#define	SENSOR_LEN			46	//dužina strukture za jedan senzor
#define	SENSOR1_START		0x00
#define	SENSOR1_CODE		SENSOR1_START
#define	SENSOR1_LOWLIMIT	SENSOR1_CODE+8	
#define	SENSOR1_HIGHLIMIT	SENSOR1_LOWLIMIT+1	
#define	SENSOR1_HIS			SENSOR1_HIGHLIMIT+1	
#define	SENSOR1_ENABLE		SENSOR1_HIS+1	
#define	SENSOR1_MAIL1		SENSOR1_ENABLE+1	
#define	SENSOR1_MAIL2		SENSOR1_MAIL1+1	
#define	SENSOR1_NAME		SENSOR1_MAIL2+1	//dužina 32 bajta

#define	SENSOR2_START		SENSOR_LEN+SENSOR1_START
#define	SENSOR2_CODE		SENSOR2_START+0x00
#define	SENSOR2_LOWLIMIT	SENSOR2_START+0x08	
#define	SENSOR2_HIGHLIMIT	SENSOR2_START+0x09	
#define	SENSOR2_HIS			SENSOR2_START+0x0A	
#define	SENSOR2_ENABLE		SENSOR2_START+0x0B
#define	SENSOR2_MAIL1		SENSOR2_START+0x0C	
#define	SENSOR2_MAIL2		SENSOR2_START+0x0D	
#define	SENSOR2_NAME		SENSOR2_START+0x0E

#define	SENSOR3_START		SENSOR_LEN+SENSOR2_START
#define	SENSOR3_CODE		SENSOR3_START+0x00
#define	SENSOR3_LOWLIMIT	SENSOR3_START+0x08	
#define	SENSOR3_HIGHLIMIT	SENSOR3_START+0x09	
#define	SENSOR3_HIS			SENSOR3_START+0x0A	
#define	SENSOR3_ENABLE		SENSOR3_START+0x0B
#define	SENSOR3_MAIL1		SENSOR3_START+0x0C	
#define	SENSOR3_MAIL2		SENSOR3_START+0x0D	
#define	SENSOR3_NAME		SENSOR3_START+0x0E

#define	SENSOR4_START		SENSOR_LEN+SENSOR3_START
#define	SENSOR4_CODE		SENSOR4_START+0x00
#define	SENSOR4_LOWLIMIT	SENSOR4_START+0x08	
#define	SENSOR4_HIGHLIMIT	SENSOR4_START+0x09	
#define	SENSOR4_HIS			SENSOR4_START+0x0A	
#define	SENSOR4_ENABLE		SENSOR4_START+0x0B
#define	SENSOR4_MAIL1		SENSOR4_START+0x0C	
#define	SENSOR4_MAIL2		SENSOR4_START+0x0D	
#define	SENSOR4_NAME		SENSOR4_START+0x0E

#define	OBJECT_NAME			SENSOR_LEN+SENSOR4_START	//dužina je 32 bajta
#endif